shareProtocols:
  - protocolSelector: NFS
    fsGroupPolicy: None
    fwdNodePluginEndpoint:
      dir: /var/lib/kubelet/plugins/csi-nfsplugin
      sockFile: csi.sock
  # - protocolSelector: CEPHFS
  #   fsGroupPolicy: None
  #   fwdNodePluginEndpoint:
  #     dir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
  #     sockFile: csi.sock

csimanila:
  pvcAnnotations: true
