apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: openstack-manila-secret
  namespace: kube-system
data:
  os-authURL: $OPENSTACK_AUTH_URL
  os-certAuthorityPath: /etc/config/endpoint-ca.crt
  os-domainName: $OPENSTACK_DOMAIN_NAME
  os-password: $OPENSTACK_PASSWORD
  os-userName: $OPENSTACK_USERNAME
  os-projectDomainName: $OPENSTACK_PROJECT_DOMAIN_NAME
  os-projectName: $OPENSTACK_PROJECT_NAME
  os-region: $OPENSTACK_REGION
