apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{SNAPSHOT_NAME}}
  namespace: {{SNAPSHOT_NAMESPACE}}
  annotations:
    manila-csi/storage-size: "{{STORAGE_SIZE}}"
spec:
  volumeSnapshotClassName: manila-csi-snapshot-class
  source:
    persistentVolumeClaimName: {{SOURCE_PVC}}
